Repository pr4shan7/beginners-only, pull requests merged in 2019-10, with the labels that each got.

#18 Create Justin.txt
  introduce-yourself/Justin.txt
Labels: first-timers-only, invalid

#11 Python
  Python/README.md
  Python/Tic-Tac-Toe/Readme.mdown
  Python/Tic-Tac-Toe/Sample.txt
  Python/Tic-Tac-Toe/TTT.py
Labels: Hacktoberfest, enhancement

#20 update from sub-branch
  Hacktoberfest/README.md
  README.md
  learning-resources/learning-resources.md
Labels: enhancement

#19 Created Folder for adding C Code, with Examples
  C/README.md
  C/base-converter.c
  C/bubblesort.c
  C/bubblesort.md
Labels: changes-requested, first-timers-only

#22 Added function to convert temperature to celsius scale
  C++/convert_tempscales.cpp
Labels: first-timers-only

#14 added-learning-resource
  README.md
Labels: Hacktoberfest, enhancement

#12 Updated learning-resources with web development
  learning-resources/learning-resources.md
Labels: Hacktoberfest, enhancement

#21 SVM added
  Machine-Learning/Algorithms/SVM/iris_classification_svm.py
  Machine-Learning/Algorithms/SVM/readme.md
Labels: Hacktoberfest, enhancement

#28 Add basic Python script with an age calculator
  Python/.idea/.gitignore
  Python/.idea/Python.iml
  Python/.idea/inspectionProfiles/profiles_settings.xml
  Python/.idea/misc.xml
  Python/.idea/modules.xml
  Python/.idea/vcs.xml
  Python/Age Calculator.py
Labels: first-timers-only

#26 Create BFS
  Python/BFS
Labels: Hacktoberfest, enhancement

#31 Added a convenient cheat sheet
  Learning-Resources/learning-resources.md
Labels: Hacktoberfest, changes-requested, enhancement

#17 Create send_message.py
  Python/send-message.py
Labels: first-timers-only

#27 Added a new learning resourse
  Learning-Resources/learning-resources.md
Labels: Hacktoberfest, enhancement

#36 guess-game-python
  Python/number-guessing-game.py
Labels: first-timers-only

#34 Create Math folder
  Math/README.md
  Math/algebra/addition/javascript/sum.js
  Math/algebra/addition/python/add.py
  Math/algebra/arithmetic/cpp/arithmetic.cpp
  Math/algebra/arithmetic/php/Arithmetic.php
  Math/algebra/arithmetic/python/arithmetic.py3
  Math/algebra/arithmetic_progression/c/arithmetic_progression.c
  Math/algebra/arithmetic_progression/java/arithmetic_progression.java
  Math/algebra/arithmetic_progression/javascript/arithmetic_progression.js
  Math/algebra/arithmetic_progression/sml/arithmetic_progression.sml
  Math/algebra/bezout/python/bezout.py
  Math/algebra/check_if_square/cpp/checkifnumisperfectsquare.cpp
  Math/geometry/arc_angle/java/ArcAngle.java
  Math/geometry/arc_angle/python/arc_angle.py
  Math/geometry/arc_area/cpp/arc_area.cpp
  Math/geometry/arc_area/python/arc_area.py
  Math/geometry/arc_length/Python/arc_length.py
  Math/geometry/arc_length/java/ArcLenght.java
  Math/geometry/area_formulas/java/HexagonArea.java
  Math/geometry/area_formulas/java/PentagonArea.java
  Math/geometry/area_formulas/java/PolygonArea.java
  Math/geometry/area_formulas/objc/area_formulas.m
  Math/geometry/area_formulas/python/area_formulas.py
  Math/phisycs/work_equations/java/WorkEquations.java
  Math/phisycs/work_equations/python/work_equations.py
Labels: enhancement, first-timers-only

#37 Math
  Math/geometry/area_plane_shapes/java/area_plane_shapes.java
  Math/geometry/circles/python/CircleFormula.py
  Math/geometry/clock_angle/java/ClockAngle.java
  Math/geometry/distance_formula/java/EuclideanDistance.java
  Math/geometry/distance_formula/java/distance_formula_2d.java
  Math/geometry/distance_formula/java/distance_formula_3d.java
  Math/geometry/distance_formula/javascript/euclidian_distance.js
  Math/geometry/distance_formula/python/distance_formula.py
  Math/geometry/distance_formula/ruby/distance_formula.rb
  Math/number_theory/fibonacci/javascript/fibonacci_number.js
  Math/number_theory/modular_exponentiation/modexp.cpp
  Math/number_theory/relative_primes/euler_totient/c/euler_totient.c
  Math/phisycs/energy_equations/cpp/Energy_Equations
  Math/phisycs/energy_equations/python/energy_equations.py
  Math/phisycs/force_equation/dart/force_equation.dart
  Math/phisycs/force_equation/elixir/force_equation.ex
  Math/phisycs/force_equation/elixir/grav_force.ex
  Math/phisycs/force_equation/java/force_equation.java
  Math/phisycs/force_equation/java/gravitational_force_equati
  Math/phisycs/force_equation/python/force_equation.py
  Math/phisycs/force_equation/python/grav_force.py
  Math/phisycs/free_fall/java/Free_Fall.java
Labels: Hacktoberfest, enhancement

#38 Add shoom1337 introduction
  introduce-yourself/shoom1337.md
Labels: first-timers-only, invalid

#39 txt
  introduce-yourself/Mukheem.md
Labels: first-timers-only, invalid

#40 SIEVE OF ERATOSTHENES
  Math/number_theory/Seive-of-Erastosthenes.cpp
Labels: Hacktoberfest, enhancement, first-timers-only

#41 Magic8ball.py
  Python/ number-guessing-game.py
  Python/Magic8Ball.py
Labels: first-timers-only, good first issue

#42 Little bit of documentation
  JavaScript/Node.js/Express.js/Beginner API/app.js
Labels: Hacktoberfest, documentation

#43 Fixed typo in title phisycs->physics
  Math/physics/energy_equations/cpp/Energy_Equations
  Math/physics/energy_equations/python/energy_equations.py
  Math/physics/force_equation/dart/force_equation.dart
  Math/physics/force_equation/elixir/force_equation.ex
  Math/physics/force_equation/elixir/grav_force.ex
  Math/physics/force_equation/java/force_equation.java
  Math/physics/force_equation/java/gravitational_force_equati
  Math/physics/force_equation/python/force_equation.py
  Math/physics/force_equation/python/grav_force.py
  Math/physics/free_fall/java/Free_Fall.java
  Math/physics/work_equations/java/WorkEquations.java
  Math/physics/work_equations/python/work_equations.py
Labels: first-timers-only

#44 Adds magicSquare.py in python folder
  Python/magicSquare.py
Labels: first-timers-only

#45 added twitter.md
  README.md
  help-from-twitter.md
Labels: Hacktoberfest, enhancement

#46 Update learning-resources.md
  Learning-Resources/learning-resources.md
Labels: Hacktoberfest, enhancement

#53 Update arithmetic_progression.c
  Math/algebra/arithmetic_progression/c/arithmetic_progression.c
Labels: first-timers-only
